---
title: Page Title
timezone: UTC
sass:
  sass_dir: _sass
  style: compressed
title: 'Zachary Montgomery'
description: 'Professional full-stack web developer; skilled at designing, building, testing, and deploying websites of all types, be they simple or complex.'
baseurl: ''
url: https://codingprojects.org
contact: 'zachmontgo@outlook.com'
logo: 'https://codingprojects.org/assets/logo.png'
theme: minima
plugins:
- jekyll-sitemap
collections:
  - projects